version: "3"
services:
  SpringBoot:
    container_name: springboot
    image: 'docker-spring-boot-postgres:latest'
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - PostgresSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sp3tJyHSn2Ay
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgresSQL:
    image: postgres
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sp3tJyHSn2Ay
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
