version: "3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "4152:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sp3tJyHSn2Ay
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
