export const fieldsData = [
  {
    id: 1,
    field: 'surname',
    label: 'Ваша фамилия',
    placeholder: 'Введите фамилию',
    type: 'text',
  },
  {
    id: 2,
    field: 'name',
    label: 'Ваше имя',
    placeholder: 'Введите имя',
    type: 'text',
  },
  {
    id: 3,
    field: 'middleName',
    label: 'Ваше отчество',
    placeholder: 'Введите отчество',
    type: 'text',
  },
  {
    id: 4,
    field: 'phone',
    label: 'Ваш телефон',
    placeholder: '+7 (999) 999-99-99',
    type: 'tel',
  },
  {
    id: 5,
    field: 'email',
    label: 'Ваш личный Email',
    placeholder: 'example@gmail.com',
    type: 'email',
  },
  {
    id: 6,
    field: 'place',
    label: 'Населенный пункт',
    placeholder: 'Населенный пункт',
    type: 'text',
  },
  {
    id: 7,
    field: 'division',
    label: 'Ваш блок или дивизион',
    placeholder: 'Укажите ваш блок или дивизион',
    type: 'text',
  },
] as const
